# Generated by Django 4.2.2 on 2023-06-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='demo_servicos')),
                ('titulo', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=100)),
                ('titulo_link', models.CharField(max_length=100)),
            ],
        ),
    ]
