# Generated by Django 4.2.2 on 2023-07-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_localizacao_mapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos_exterior_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='image_exterior')),
                ('titulo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '1.6 Fotos exterior/ pagina inicial',
            },
        ),
        migrations.CreateModel(
            name='Fotos_quartos_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='image_quartos')),
                ('titulo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '1.7 Fotos quartos/ pagina inicial',
            },
        ),
        migrations.CreateModel(
            name='Fotos_restaurante_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='image_restaurante')),
                ('titulo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '1.8 Fotos restaurante/ pagina inicial',
            },
        ),
        migrations.AlterModelOptions(
            name='banner_auditorio',
            options={'verbose_name_plural': '2.1 Banner/ auditorio'},
        ),
        migrations.AlterModelOptions(
            name='banner_jardim',
            options={'verbose_name_plural': '2.7 Banner/ Jardim eventos'},
        ),
        migrations.AlterModelOptions(
            name='banner_jardim_infantil',
            options={'verbose_name_plural': '2.9 Banner/ Jardim infantil'},
        ),
        migrations.AlterModelOptions(
            name='banner_piscina',
            options={'verbose_name_plural': '2.5 Banner/ piscina'},
        ),
        migrations.AlterModelOptions(
            name='banner_quartos',
            options={'verbose_name_plural': '2.3 Banner/ quartos'},
        ),
        migrations.AlterModelOptions(
            name='banner_restaurante',
            options={'verbose_name_plural': '1.9 Banner/ restaurante'},
        ),
        migrations.AlterModelOptions(
            name='fotos_all_auditorio',
            options={'verbose_name_plural': '2.2 Fotos/ auditorio'},
        ),
        migrations.AlterModelOptions(
            name='fotos_all_jardim',
            options={'verbose_name_plural': '2.8 Fotos/ Jardim eventos'},
        ),
        migrations.AlterModelOptions(
            name='fotos_all_jardim_infantil',
            options={'verbose_name_plural': '3.0 Fotos/ Jardim infantil'},
        ),
        migrations.AlterModelOptions(
            name='fotos_all_piscina',
            options={'verbose_name_plural': '2.6 Fotos/ piscina'},
        ),
        migrations.AlterModelOptions(
            name='fotos_all_quartos',
            options={'verbose_name_plural': '2.4 Fotos/ quartos'},
        ),
        migrations.AlterModelOptions(
            name='fotos_all_restaurante',
            options={'verbose_name_plural': '2.0 Fotos/ restaurante'},
        ),
        migrations.AlterModelOptions(
            name='localizacao_mapa',
            options={'verbose_name_plural': '3.1 Localizacao/ mapa'},
        ),
    ]
