# Generated by Django 4.2.2 on 2023-07-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_fotos_exterior_home_fotos_quartos_home_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localizacao_mapa',
            name='mapa',
        ),
    ]
