# Generated by Django 4.2.2 on 2023-07-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_fotos_outras_quartos_fotos_outras_restaurante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quartos_preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imahem_quartos')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='banner_auditorio',
            options={'verbose_name_plural': '2.3 Banner/ auditorio'},
        ),
        migrations.AlterModelOptions(
            name='banner_jardim',
            options={'verbose_name_plural': '3.1 Banner/ Jardim eventos'},
        ),
        migrations.AlterModelOptions(
            name='banner_jardim_infantil',
            options={'verbose_name_plural': '3.3 Banner/ Jardim infantil'},
        ),
        migrations.AlterModelOptions(
            name='banner_piscina',
            options={'verbose_name_plural': '2.9 Banner/ piscina'},
        ),
        migrations.AlterModelOptions(
            name='banner_quartos',
            options={'verbose_name_plural': '2.5 Banner/ quartos'},
        ),
        migrations.AlterModelOptions(
            name='fotos_all_auditorio',
            options={'verbose_name_plural': '2.4 Fotos/ auditorio'},
        ),
        migrations.AlterModelOptions(
            name='fotos_all_jardim',
            options={'verbose_name_plural': '3.2 Fotos/ Jardim eventos'},
        ),
        migrations.AlterModelOptions(
            name='fotos_all_jardim_infantil',
            options={'verbose_name_plural': '3.4 Fotos/ Jardim infantil'},
        ),
        migrations.AlterModelOptions(
            name='fotos_all_piscina',
            options={'verbose_name_plural': '3.0 Fotos/ piscina'},
        ),
        migrations.AlterModelOptions(
            name='fotos_all_quartos',
            options={'verbose_name_plural': '2.6 Todas Fotos/ quartos'},
        ),
        migrations.AlterModelOptions(
            name='fotos_outras_quartos',
            options={'verbose_name_plural': '2.8 Fotos outras/ quartos'},
        ),
        migrations.AlterModelOptions(
            name='fotos_outras_restaurante',
            options={'verbose_name_plural': '2.2 Fotos outras/ restaurante'},
        ),
        migrations.AlterModelOptions(
            name='fotos_quartos',
            options={'verbose_name_plural': '2.7 Fotos quartos/ quartos'},
        ),
        migrations.AlterModelOptions(
            name='fotos_restaurante',
            options={'verbose_name_plural': '2.1 Fotos restaurante/ restaurante'},
        ),
        migrations.AlterModelOptions(
            name='localizacao_mapa',
            options={'verbose_name_plural': '3.5 Localizacao/ mapa'},
        ),
    ]
