# Generated by Django 4.2.2 on 2023-07-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_quartos_preco_alter_banner_auditorio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartos_preco',
            name='preco',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
