# Generated by Django 4.2.2 on 2023-06-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_demoservicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icon_contacto')),
                ('link', models.CharField(max_length=200)),
                ('contacto', models.CharField(max_length=200)),
            ],
        ),
    ]
