# Generated by Django 4.2.2 on 2023-06-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_iconcontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='all_image')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
    ]
