# Generated by Django 4.2.2 on 2023-06-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_fotos_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_auditorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='banner_aud')),
            ],
            options={
                'verbose_name_plural': '1.8 Banner/ auditorio',
            },
        ),
        migrations.CreateModel(
            name='Banner_jardim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='banner_jardim_')),
            ],
            options={
                'verbose_name_plural': '2.9 Banner/ Jardim eventos',
            },
        ),
        migrations.CreateModel(
            name='Banner_jardim_infantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='banner_jardim_infantil')),
            ],
            options={
                'verbose_name_plural': '3.2 Banner/ Jardim infantil',
            },
        ),
        migrations.CreateModel(
            name='Banner_piscina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='banner_piscina')),
            ],
            options={
                'verbose_name_plural': '2.3 Banner/ piscina',
            },
        ),
        migrations.CreateModel(
            name='Banner_quartos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='banner_quartos')),
            ],
            options={
                'verbose_name_plural': '2.1 Banner/ quartos',
            },
        ),
        migrations.CreateModel(
            name='Banner_restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='banner_rest')),
            ],
            options={
                'verbose_name_plural': '1.6 Banner/ restaurante',
            },
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='icon')),
            ],
            options={
                'verbose_name_plural': '1.3 Contactos/ pagina inicial',
            },
        ),
        migrations.CreateModel(
            name='Fotos_all_auditorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='all_image_aud')),
            ],
            options={
                'verbose_name_plural': '1.9 Fotos/ auditorio',
            },
        ),
        migrations.CreateModel(
            name='Fotos_all_jardim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='all_image_jardim_')),
            ],
            options={
                'verbose_name_plural': '3.1 Fotos/ Jardim eventos',
            },
        ),
        migrations.CreateModel(
            name='Fotos_all_jardim_infantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='all_image_jardim_infantil')),
            ],
            options={
                'verbose_name_plural': '3.3 Fotos/ Jardim infantil',
            },
        ),
        migrations.CreateModel(
            name='Fotos_all_piscina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='all_image_piscina')),
            ],
            options={
                'verbose_name_plural': '2.4 Fotos/ piscina',
            },
        ),
        migrations.CreateModel(
            name='Fotos_all_quartos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='all_image_quartos')),
            ],
            options={
                'verbose_name_plural': '2.2 Fotos/ quartos',
            },
        ),
        migrations.CreateModel(
            name='Fotos_all_restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='all_image_rest')),
            ],
            options={
                'verbose_name_plural': '1.7 Fotos/ restaurante',
            },
        ),
        migrations.CreateModel(
            name='Siga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='icon')),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '1.4 Siga-nos/ pagina inicial',
            },
        ),
        migrations.DeleteModel(
            name='IconContacto',
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '1. Banner/ pagina inicial'},
        ),
        migrations.AlterModelOptions(
            name='demoservicos',
            options={'verbose_name_plural': '1.2 Imagens/ portfolio pagina inicial'},
        ),
        migrations.AlterModelOptions(
            name='fotos_all',
            options={'verbose_name_plural': '1.5 Fotos/ pagina inicial'},
        ),
    ]
